from dataclasses import dataclass, field

from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, ConfigDict, Field

from openhound_github.graph import GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app


@dataclass
class GHBranchProperties(GHNodeProperties):
    """Branch-specific properties and accordion panel queries."""

    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )
    short_name: str = field(
        default="",
        metadata={"description": "The branch reference name (e.g., `main`)."},
    )
    commit_hash: str | None = None
    protected: bool = field(
        default=False,
        metadata={"description": "Whether the branch has a protection rule."},
    )
    repository_name: str = ""
    repository_id: str = ""
    environment_name: str = field(
        default="",
        metadata={"description": "The name of the environment (GitHub organization)."},
    )
    query_branch_write: str = ""


class ProtectionRule(BaseModel):
    id: str


@app.asset(
    node=NodeDef(
        kind=nk.BRANCH,
        description="GitHub Branch",
        icon="code-branch",
        properties=GHBranchProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.REPOSITORY,
            end=nk.BRANCH,
            kind=ek.HAS_BRANCH,
            description="Repository has branch",
            traversable=False,
        ),
        EdgeDef(
            start=nk.BRANCH_PROTECTION_RULE,
            end=nk.BRANCH,
            kind=ek.PROTECTED_BY,
            description="Branch is protected by rule",
            traversable=True,
        ),
    ],
)
class Branch(BaseAsset):
    """One record from the `branches` DLT table → one GH_Branch node + GH_HasBranch edge + optional GH_ProtectedBy edge."""

    model_config = ConfigDict(populate_by_name=True)
    id: str
    name: str
    target: dict
    repository_node_id: str
    repository_name: str
    branch_protection_rule: ProtectionRule | None = Field(
        alias="branchProtectionRule", default=None
    )

    # Additional
    org_login: str

    @property
    def node_id(self) -> str:
        """The ID is identical to a node_id when using GraphQL"""
        return self.id

    @property
    def as_node(self) -> GHNode:
        return GHNode(
            kinds=[nk.BRANCH],
            properties=GHBranchProperties(
                name=f"{self.repository_name}/{self.name}",
                displayname=self.name,
                node_id=self.node_id,
                short_name=self.name,
                commit_hash=self.target.get("oid"),
                protected=self.branch_protection_rule is not None,
                repository_name=self.repository_name,
                repository_id=self.repository_node_id,
                environment_name=self._lookup.org_login(),
                environmentid=self._lookup.org_id(),
                query_branch_write=(
                    f"MATCH p=(:GH_User)-[:GH_CanWriteBranch|GH_CanEditAndWriteBranch]"
                    f"->(:GH_Branch {{node_id:'{self.node_id}'}}) RETURN p"
                ),
            ),
        )

    @property
    def _protection_edge(self):
        if self.branch_protection_rule:
            yield Edge(
                kind=ek.PROTECTED_BY,
                start=EdgePath(value=self.branch_protection_rule.id, match_by="id"),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        yield Edge(
            kind=ek.HAS_BRANCH,
            start=EdgePath(value=self.repository_node_id, match_by="id"),
            end=EdgePath(value=self.node_id, match_by="id"),
            properties=EdgeProperties(traversable=False),
        )
        yield from self._protection_edge
