from dataclasses import dataclass, field
from typing import ClassVar

from dlt.common.libs.pydantic import DltConfig
from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel

from openhound_github.graph import GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app


class DeploymentBranchPolicy(BaseModel):
    protected_branches: bool
    custom_branch_policies: bool


class User(BaseModel):
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool


class Team(BaseModel):
    id: int
    node_id: str
    url: str
    html_url: str
    name: str
    slug: str
    description: str
    privacy: str
    notification_setting: str
    permission: str
    members_url: str
    repositories_url: str
    parent: dict | None = None


class Reviewer(BaseModel):
    type: str
    reviewer: dict | None = None


class ProtectionRule(BaseModel):
    id: int
    node_id: str
    type: str
    wait_timer: int | None = None
    prevent_self_review: bool | None = None
    reviewers: list[Reviewer] | None = None


@dataclass
class GHEnvironmentProperties(GHNodeProperties):
    """Environment-specific properties and accordion panel queries."""

    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )
    short_name: str = field(
        default="",
        metadata={
            "description": "The environment's display name (e.g., `production`, `staging`)."
        },
    )
    can_admins_bypass: bool | None = field(
        default=None,
        metadata={
            "description": "Whether repository administrators can bypass environment protection rules."
        },
    )
    repository_name: str = field(
        default="",
        metadata={"description": "The full name of the containing repository."},
    )
    repository_id: str = field(
        default="", metadata={"description": "The ID of the containing repository."}
    )
    environment_name: str = field(
        default="",
        metadata={"description": "The name of the environment (GitHub organization)."},
    )


@app.asset(
    node=NodeDef(
        kind=nk.ENVIRONMENT,
        description="GitHub Deployment Environment",
        icon="leaf",
        properties=GHEnvironmentProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.REPOSITORY,
            end=nk.ENVIRONMENT,
            kind=ek.HAS_ENVIRONMENT,
            description="Repository deploys to environment (no custom branch policy)",
            traversable=True,
        ),
    ],
)
class Environment(BaseAsset):
    """One record from `environments` → one GH_Environment node.

    GH_HasEnvironment edge from repo is only emitted when has_custom_branch_policies=False.
    When True, EnvironmentBranchPolicyAsset emits the edges instead.
    """

    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    id: int
    node_id: str
    name: str
    url: str
    html_url: str
    created_at: str
    updated_at: str
    protection_rules: list[ProtectionRule] | None = None
    deployment_branch_policy: DeploymentBranchPolicy | None = None

    # Custom fields added
    org_login: str
    repository_name: str
    repository_full_name: str
    repository_node_id: str

    @property
    def org_node_id(self) -> str | None:
        return self._lookup.org_id_for_login(self.org_login)

    @property
    def has_custom_branch_policies(self) -> bool:
        if self.deployment_branch_policy:
            return self.deployment_branch_policy.custom_branch_policies
        return False

    @property
    def as_node(self) -> GHNode:
        eid = self.node_id
        return GHNode(
            kinds=[nk.ENVIRONMENT],
            properties=GHEnvironmentProperties(
                name=self.name,
                displayname=self.name,
                node_id=eid,
                short_name=self.name,
                # can_admins_bypass=self.can_admins_bypass,
                repository_name=self.repository_name,
                repository_id=self.repository_node_id,
                environment_name=self.org_login,
                environmentid=self.org_node_id,
            ),
        )

    @property
    def edges(self):
        # TODO: Check if correct
        if not self.has_custom_branch_policies:
            yield Edge(
                kind=ek.HAS_ENVIRONMENT,
                start=EdgePath(value=self.repository_node_id, match_by="id"),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )
