from dataclasses import dataclass
from typing import ClassVar

from dlt.common.libs.pydantic import DltConfig
from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel

from openhound_github.graph import GHEdgeProperties, GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app
from openhound_github.models.environment_branch_policy import (
    matches_environment_branch_policy,
)


class DeploymentBranchPolicy(BaseModel):
    protected_branches: bool
    custom_branch_policies: bool


class User(BaseModel):
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool


class Team(BaseModel):
    id: int
    node_id: str
    url: str
    html_url: str
    name: str
    slug: str
    description: str
    privacy: str
    notification_setting: str
    permission: str
    members_url: str
    repositories_url: str
    parent: dict | None = None


class Reviewer(BaseModel):
    type: str
    reviewer: dict | None = None


class ProtectionRule(BaseModel):
    id: int
    node_id: str
    type: str
    wait_timer: int | None = None
    prevent_self_review: bool | None = None
    reviewers: list[Reviewer] | None = None


@dataclass
class GHEnvironmentProperties(GHNodeProperties):
    """Environment-specific properties and accordion panel queries.

    Attributes:
        collected: Collected/generated by OpenHound
        short_name: The environment's display name (e.g., `production`, `staging`).
        can_admins_bypass: Whether repository administrators can bypass environment protection rules.
        repository_name: The full name of the containing repository.
        repository_id: The ID of the containing repository.
        environment_name: The name of the environment (GitHub organization).
    """

    collected: bool = True
    short_name: str | None = None
    can_admins_bypass: bool | None = None
    wait_timer: int | None = None
    required_reviewers: bool = False
    reviewer_count: int = 0
    prevent_self_review: bool | None = None
    protected_branches: bool | None = None
    custom_branch_policies: bool | None = None
    repository_name: str | None = None
    repository_id: str | None = None
    environment_name: str | None = None


@app.asset(
    node=NodeDef(
        kind=nk.ENVIRONMENT,
        description="GitHub Deployment Environment",
        icon="leaf",
        properties=GHEnvironmentProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.REPOSITORY,
            end=nk.ENVIRONMENT,
            kind=ek.CONTAINS,
            description="Repository contains environment",
            traversable=False,
        ),
        EdgeDef(
            start=nk.REPO_ROLE,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_EDIT_ENVIRONMENT,
            description="Repository admin role can edit environment configuration",
            traversable=True,
        ),
        EdgeDef(
            start=nk.REPOSITORY,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
            description="Repository can deploy to environment under current branch policy",
            traversable=True,
        ),
        EdgeDef(
            start=nk.BRANCH,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
            description="Branch can deploy to environment under current branch policy",
            traversable=True,
        ),
        EdgeDef(
            start=nk.REPO_ROLE,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
            description="Repository admin-equivalent role can bypass environment protections",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
            description="Reviewer user can self-approve and supply deployable code under current branch policy",
            traversable=True,
        ),
        EdgeDef(
            start=nk.TEAM,
            end=nk.ENVIRONMENT,
            kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
            description="Reviewer team can self-approve and supply deployable code under current branch policy",
            traversable=True,
        ),
        EdgeDef(
            start=nk.USER,
            end=nk.ENVIRONMENT,
            kind=ek.APPROVES_DEPLOYMENT_TO,
            description="User is configured as a required reviewer for this environment",
            traversable=False,
        ),
        EdgeDef(
            start=nk.TEAM,
            end=nk.ENVIRONMENT,
            kind=ek.APPROVES_DEPLOYMENT_TO,
            description="Team is configured as a required reviewer for this environment",
            traversable=False,
        ),
    ],
)
class Environment(BaseAsset):
    """One record from `environments` → one GH_Environment node.

    The repository always contains the environment. Deployment eligibility is
    represented separately by computed GH_CanDeployToEnvironment edges.
    """

    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    id: int
    node_id: str
    name: str
    url: str
    html_url: str
    created_at: str
    updated_at: str
    protection_rules: list[ProtectionRule] | None = None
    deployment_branch_policy: DeploymentBranchPolicy | None = None
    can_admins_bypass: bool | None = None

    # Custom fields added
    org_login: str
    repository_name: str
    repository_full_name: str
    repository_node_id: str

    @property
    def org_node_id(self) -> str | None:
        return self._lookup.org_id_for_login(self.org_login)

    @property
    def has_custom_branch_policies(self) -> bool:
        if self.deployment_branch_policy:
            return self.deployment_branch_policy.custom_branch_policies
        return False

    @property
    def wait_timer(self) -> int:
        for rule in self.protection_rules or []:
            if rule.type == "wait_timer":
                return rule.wait_timer or 0
        return 0

    @property
    def required_reviewers(self) -> bool:
        return any(
            rule.type == "required_reviewers"
            for rule in (self.protection_rules or [])
        )

    @property
    def prevent_self_review(self) -> bool:
        for rule in self.protection_rules or []:
            if rule.type == "required_reviewers":
                return bool(rule.prevent_self_review)
        return False

    @property
    def reviewers(self) -> list[Reviewer]:
        for rule in self.protection_rules or []:
            if rule.type == "required_reviewers":
                return rule.reviewers or []
        return []

    @property
    def source_deployment_edges_allowed(self) -> bool:
        return not self.required_reviewers

    @property
    def reviewer_self_deployment_edges_allowed(self) -> bool:
        return self.required_reviewers and not self.prevent_self_review

    @property
    def _reviewer_eligible_branch_ids(self) -> tuple[str, ...]:
        branches = self._lookup.branches_for_repository(self.repository_node_id)

        if self.has_custom_branch_policies:
            protected_branches_only = bool(
                self.deployment_branch_policy
                and self.deployment_branch_policy.protected_branches
            )
            policy_names = {
                policy_name
                for (policy_name,) in self._lookup.environment_branch_policy_names(
                    self.node_id
                )
            }
            return tuple(
                branch_id
                for branch_id, branch_name, protected in branches
                if any(
                    matches_environment_branch_policy(branch_name, policy_name)
                    for policy_name in policy_names
                )
                and (not protected_branches_only or protected)
            )

        if (
            self.deployment_branch_policy
            and self.deployment_branch_policy.protected_branches
        ):
            protected_branch_ids = tuple(
                branch_id
                for (branch_id,) in self._lookup.branches_with_bpr(
                    self.repository_node_id
                )
            )
            if protected_branch_ids:
                return protected_branch_ids

        return tuple(branch_id for branch_id, _branch_name, _protected in branches)

    @property
    def _reviewer_can_create_branch_for_deployment(self) -> bool:
        return not self.has_custom_branch_policies and not (
            self.deployment_branch_policy
            and self.deployment_branch_policy.protected_branches
        )

    @property
    def as_node(self) -> GHNode:
        eid = self.node_id
        return GHNode(
            kinds=[nk.ENVIRONMENT],
            properties=GHEnvironmentProperties(
                name=self.name,
                displayname=self.name,
                node_id=eid,
                short_name=self.name,
                can_admins_bypass=self.can_admins_bypass,
                wait_timer=self.wait_timer,
                required_reviewers=self.required_reviewers,
                reviewer_count=len(self.reviewers),
                prevent_self_review=self.prevent_self_review,
                protected_branches=bool(
                    self.deployment_branch_policy.protected_branches
                ) if self.deployment_branch_policy else False,
                custom_branch_policies=bool(
                    self.deployment_branch_policy.custom_branch_policies
                ) if self.deployment_branch_policy else False,
                repository_name=self.repository_name,
                repository_id=self.repository_node_id,
                environment_name=self.org_login,
                environmentid=self.org_node_id,
            ),
        )

    def _repo_can_deploy_query(self) -> str:
        return (
            f"MATCH p=(:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE coalesce(env.custom_branch_policies, false) = false "
            f"AND coalesce(env.protected_branches, false) = false "
            f"AND coalesce(env.required_reviewers, false) = false "
            f"RETURN p"
        )

    def _branch_can_deploy_via_repo_query(self, branch_id: str) -> str:
        return (
            f"MATCH p=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(:GH_Branch {{node_id:'{branch_id}'}}) "
            f"MATCH p1=(repo)-[:GH_Contains]->"
            f"(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE coalesce(env.custom_branch_policies, false) = false "
            f"AND coalesce(env.protected_branches, false) = false "
            f"AND coalesce(env.required_reviewers, false) = false "
            f"RETURN p, p1"
        )

    def _protected_branch_can_deploy_query(self, branch_id: str) -> str:
        return (
            f"MATCH p=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(:GH_Branch {{node_id:'{branch_id}'}})"
            f"<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
            f"MATCH p1=(repo)-[:GH_Contains]->"
            f"(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE coalesce(env.custom_branch_policies, false) = false "
            f"AND env.protected_branches = true "
            f"AND coalesce(env.required_reviewers, false) = false "
            f"RETURN p, p1"
        )

    def _admin_bypass_query(self) -> str:
        admin_role_id = f"{self.repository_node_id}_admin"
        return (
            f"MATCH p=(:GH_RepoRole {{node_id:'{admin_role_id}'}})"
            f"-[:GH_AdminTo]->(:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE env.can_admins_bypass = true "
            f"RETURN p"
        )

    def _reviewer_can_create_branch_query(
        self, reviewer_node_id: str, reviewer_kind: str
    ) -> str:
        return (
            f"MATCH p=(actor:{reviewer_kind} {{node_id:'{reviewer_node_id}'}})"
            f"-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf*1..]->"
            f"(:GH_RepoRole)-[:GH_CanCreateBranch]->"
            f"(repo:GH_Repository {{node_id:'{self.repository_node_id}'}}) "
            f"MATCH p1=(actor)-[:GH_ApprovesDeploymentTo]->"
            f"(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"MATCH p2=(repo)-[:GH_Contains]->(env) "
            f"WHERE env.required_reviewers = true "
            f"AND coalesce(env.prevent_self_review, false) = false "
            f"AND coalesce(env.custom_branch_policies, false) = false "
            f"AND coalesce(env.protected_branches, false) = false "
            f"RETURN p, p1, p2"
        )

    def _reviewer_can_write_branch_query(
        self, reviewer_node_id: str, reviewer_kind: str, branch_id: str
    ) -> str:
        actor_path = (
            f"MATCH p=(actor:{reviewer_kind} {{node_id:'{reviewer_node_id}'}})"
            f"-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf|GH_CanWriteBranch*1..]->"
            f"(branch:GH_Branch {{node_id:'{branch_id}'}}) "
            f"MATCH p1=(actor)-[:GH_ApprovesDeploymentTo]->"
            f"(env:GH_Environment {{node_id:'{self.node_id}'}}) "
        )
        reviewer_policy = (
            "WHERE env.required_reviewers = true "
            "AND coalesce(env.prevent_self_review, false) = false "
        )

        if self.has_custom_branch_policies:
            custom_policy_path = (
                "MATCH p2=(branch)-[:GH_MatchesEnvironmentPolicy]->"
                "(:GH_EnvironmentBranchPolicy)<-[:GH_Contains]-(env) "
            )
            if (
                self.deployment_branch_policy
                and self.deployment_branch_policy.protected_branches
            ):
                return (
                    actor_path
                    + custom_policy_path
                    + "MATCH p3=(branch)<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
                    + reviewer_policy
                    + "AND env.custom_branch_policies = true "
                    + "AND env.protected_branches = true "
                    + "RETURN p, p1, p2, p3"
                )

            return (
                actor_path
                + custom_policy_path
                + reviewer_policy
                + "AND env.custom_branch_policies = true "
                + "AND coalesce(env.protected_branches, false) = false "
                + "RETURN p, p1, p2"
            )

        if (
            self.deployment_branch_policy
            and self.deployment_branch_policy.protected_branches
        ):
            if self._lookup.branches_with_bpr(self.repository_node_id):
                return (
                    actor_path
                    + f"MATCH p2=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
                    f"-[:GH_Contains]->(branch)<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
                    f"MATCH p3=(repo)-[:GH_Contains]->(env) "
                    + reviewer_policy
                    + "AND env.protected_branches = true "
                    + "AND coalesce(env.custom_branch_policies, false) = false "
                    + "RETURN p, p1, p2, p3"
                )

            return (
                actor_path
                + f"MATCH p2=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
                f"-[:GH_Contains]->(branch) "
                f"MATCH p3=(repo)-[:GH_Contains]->(env) "
                + reviewer_policy
                + "AND env.protected_branches = true "
                + "AND coalesce(env.custom_branch_policies, false) = false "
                + "AND NOT EXISTS { "
                + "MATCH (repo)-[:GH_Contains]->(:GH_Branch)"
                + "<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
                + "} "
                + "RETURN p, p1, p2, p3"
            )

        return (
            actor_path
            + f"MATCH p2=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(branch) "
            f"MATCH p3=(repo)-[:GH_Contains]->(env) "
            + reviewer_policy
            + "AND coalesce(env.custom_branch_policies, false) = false "
            + "AND coalesce(env.protected_branches, false) = false "
            + "RETURN p, p1, p2, p3"
        )

    def _protected_branches_fallback_repo_query(self) -> str:
        return (
            f"MATCH p=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE env.protected_branches = true "
            f"AND coalesce(env.custom_branch_policies, false) = false "
            f"AND coalesce(env.required_reviewers, false) = false "
            f"AND NOT EXISTS {{ "
            f"MATCH (repo)-[:GH_Contains]->(:GH_Branch)"
            f"<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
            f"}} "
            f"RETURN p"
        )

    def _protected_branches_fallback_branch_query(self, branch_id: str) -> str:
        return (
            f"MATCH p=(repo:GH_Repository {{node_id:'{self.repository_node_id}'}})"
            f"-[:GH_Contains]->(:GH_Branch {{node_id:'{branch_id}'}}) "
            f"MATCH p1=(repo)-[:GH_Contains]->"
            f"(env:GH_Environment {{node_id:'{self.node_id}'}}) "
            f"WHERE env.protected_branches = true "
            f"AND coalesce(env.custom_branch_policies, false) = false "
            f"AND coalesce(env.required_reviewers, false) = false "
            f"AND NOT EXISTS {{ "
            f"MATCH (repo)-[:GH_Contains]->(:GH_Branch)"
            f"<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) "
            f"}} "
            f"RETURN p, p1"
        )

    @property
    def edges(self):
        yield Edge(
            kind=ek.CONTAINS,
            start=EdgePath(value=self.repository_node_id, match_by="id"),
            end=EdgePath(value=self.node_id, match_by="id"),
            properties=EdgeProperties(traversable=False),
        )

        yield Edge(
            kind=ek.CAN_EDIT_ENVIRONMENT,
            start=EdgePath(
                value=f"{self.repository_node_id}_admin",
                match_by="id",
            ),
            end=EdgePath(value=self.node_id, match_by="id"),
            properties=EdgeProperties(traversable=True),
        )

        if self.source_deployment_edges_allowed and not self.has_custom_branch_policies and not (
            self.deployment_branch_policy
            and self.deployment_branch_policy.protected_branches
        ):
            yield Edge(
                kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                start=EdgePath(value=self.repository_node_id, match_by="id"),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=GHEdgeProperties(
                    traversable=True,
                    composed=True,
                    query_composition=self._repo_can_deploy_query(),
                ),
            )

            branches = self._lookup.branches_for_repository(self.repository_node_id)
            for branch_id, _branch_name, _protected in branches:
                yield Edge(
                    kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                    start=EdgePath(value=branch_id, match_by="id"),
                    end=EdgePath(value=self.node_id, match_by="id"),
                    properties=GHEdgeProperties(
                        traversable=True,
                        composed=True,
                        query_composition=self._branch_can_deploy_via_repo_query(branch_id),
                    ),
                )

        if self.source_deployment_edges_allowed and not self.has_custom_branch_policies and (
            self.deployment_branch_policy
            and self.deployment_branch_policy.protected_branches
        ):
            protected_branches = self._lookup.branches_with_bpr(self.repository_node_id)

            if protected_branches:
                for (branch_id,) in protected_branches:
                    yield Edge(
                        kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                        start=EdgePath(value=branch_id, match_by="id"),
                        end=EdgePath(value=self.node_id, match_by="id"),
                        properties=GHEdgeProperties(
                            traversable=True,
                            composed=True,
                            query_composition=self._protected_branch_can_deploy_query(branch_id),
                        ),
                    )
            else:
                yield Edge(
                    kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                    start=EdgePath(value=self.repository_node_id, match_by="id"),
                    end=EdgePath(value=self.node_id, match_by="id"),
                    properties=GHEdgeProperties(
                        traversable=True,
                        composed=True,
                        query_composition=self._protected_branches_fallback_repo_query(),
                    ),
                )

                for branch_id, _branch_name, _protected in self._lookup.branches_for_repository(
                    self.repository_node_id
                ):
                    yield Edge(
                        kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                        start=EdgePath(value=branch_id, match_by="id"),
                        end=EdgePath(value=self.node_id, match_by="id"),
                        properties=GHEdgeProperties(
                            traversable=True,
                            composed=True,
                            query_composition=self._protected_branches_fallback_branch_query(branch_id),
                        ),
                    )

        if self.can_admins_bypass:
            yield Edge(
                kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                start=EdgePath(
                    value=f"{self.repository_node_id}_admin",
                    match_by="id",
                ),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=GHEdgeProperties(
                    traversable=True,
                    composed=True,
                    query_composition=self._admin_bypass_query(),
                ),
            )

        for reviewer in self.reviewers:
            reviewer_data = reviewer.reviewer or {}
            reviewer_node_id = reviewer_data.get("node_id")
            if not reviewer_node_id:
                continue

            reviewer_type = reviewer.type.lower()
            if reviewer_type not in {"user", "team"}:
                continue

            yield Edge(
                kind=ek.APPROVES_DEPLOYMENT_TO,
                start=EdgePath(value=reviewer_node_id, match_by="id"),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=EdgeProperties(traversable=False),
            )

            if self.reviewer_self_deployment_edges_allowed:
                reviewer_kind = nk.USER if reviewer_type == "user" else nk.TEAM
                deployment_path = self._lookup.reviewer_deployment_path(
                    reviewer_node_id,
                    reviewer_type,
                    self.repository_node_id,
                    self._reviewer_eligible_branch_ids,
                    self._reviewer_can_create_branch_for_deployment,
                )
                if deployment_path is None:
                    continue

                path_type, branch_id = deployment_path
                query_composition = (
                    self._reviewer_can_create_branch_query(
                        reviewer_node_id, reviewer_kind
                    )
                    if path_type == "create_branch"
                    else self._reviewer_can_write_branch_query(
                        reviewer_node_id, reviewer_kind, branch_id or ""
                    )
                )
                yield Edge(
                    kind=ek.CAN_DEPLOY_TO_ENVIRONMENT,
                    start=EdgePath(value=reviewer_node_id, match_by="id"),
                    end=EdgePath(value=self.node_id, match_by="id"),
                    properties=GHEdgeProperties(
                        traversable=True,
                        composed=True,
                        query_composition=query_composition,
                    ),
                )
