from dataclasses import dataclass
from typing import ClassVar

from dlt.common.libs.pydantic import DltConfig
from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, Field

from openhound_github.graph import GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app


@dataclass
class GHRepositoryProperties(GHNodeProperties):
    """Repository-specific properties and accordion panel queries.
    
    Attributes:
        collected: Collected/generated by OpenHound
        full_name: The fully qualified name (e.g., `org/repo`).
        private: Whether the repository is private.
        html_url: URL to the repository on GitHub.
        description: The repository description.
        created_at: When the repository was created.
        updated_at: When the repository was last updated.
        pushed_at: When the repository last had a push.
        archived: Whether the repository is archived.
        disabled: Whether the repository is disabled.
        visibility: The visibility level: `public`, `private`, or `internal`.
        default_branch: The name of the default branch (e.g., `main`).
        open_issues_count: Number of open issues.
        allow_forking: Whether forking is allowed.
        web_commit_signoff_required: Whether web-based commits require sign-off.
        forks: Number of forks.
        open_issues: Number of open issues (includes pull requests).
        watchers: Number of watchers.
        owner_name: The login of the repository owner.
        owner_id: The owner id property.
        environment_name: The name of the environment (GitHub organization).
        actions_enabled: Whether GitHub Actions is enabled for this repository.
        self_hosted_runners_enabled: Whether the repository may use self-hosted runners.
        secret_scanning: Status of secret scanning (e.g., `enabled`, `disabled`).
        query_branches: Query for branches.
        query_protected_branches: Query for protected branches.
        query_branch_protection_rules: Query for branch protection rules.
        query_roles: Query for roles.
        query_teams: Query for teams.
        query_workflows: Query for workflows.
        query_runners: Query for runners.
        query_environments: Query for environments.
        query_secrets: Query for secrets.
        query_variables: Query for variables.
        query_secret_scanning_alerts: Query for secret scanning alerts.
        query_explicit_readers: Query for explicit readers.
        query_unrolled_readers: Query for unrolled readers.
        query_explicit_writers: Query for explicit writers.
        query_unrolled_writers: Query for unrolled writers.
    """

    collected: bool = True

    # TODO: Check owner_node_id
    full_name: str | None = None
    private: bool | None = None
    html_url: str | None = None
    description: str | None = None
    created_at: str | None = None
    updated_at: str | None = None
    pushed_at: str | None = None
    archived: bool | None = None
    disabled: bool | None = None
    visibility: str | None = None
    default_branch: str | None = None
    open_issues_count: int | None = None
    allow_forking: bool | None = None
    web_commit_signoff_required: bool | None = None
    forks: int | None = None
    open_issues: int | None = None
    watchers: int | None = None
    owner_name: str | None = None
    owner_id: str | None = None
    environment_name: str | None = None
    actions_enabled: bool | None = None
    self_hosted_runners_enabled: bool | None = None
    secret_scanning: str | None = None
    query_branches: str | None = None
    query_protected_branches: str | None = None
    query_branch_protection_rules: str | None = None
    query_roles: str | None = None
    query_teams: str | None = None
    query_workflows: str | None = None
    query_runners: str | None = None
    query_environments: str | None = None
    query_secrets: str | None = None
    query_variables: str | None = None
    query_secret_scanning_alerts: str | None = None
    query_explicit_readers: str | None = None
    query_unrolled_readers: str | None = None
    query_explicit_writers: str | None = None
    query_unrolled_writers: str | None = None


class Owner(BaseModel):
    login: str
    id: int
    node_id: str
    avatar_url: str
    gravatar_id: str
    url: str
    html_url: str
    followers_url: str
    following_url: str
    gists_url: str
    starred_url: str
    subscriptions_url: str
    organizations_url: str
    repos_url: str
    events_url: str
    received_events_url: str
    type: str
    site_admin: bool


class PageInfo(BaseModel):
    end_cursor: str | None = Field(alias="endCursor", default=None)
    has_next_page: bool = Field(alias="hasNextPage")


class Branch(BaseModel):
    id: str
    name: str
    target: dict
    branch_protection_rule: dict | None = Field(
        alias="branchProtectionRule", default=None
    )


class Ref(BaseModel):
    page_info: PageInfo = Field(alias="pageInfo")
    nodes: list[Branch]


class RepositoryQL(BaseModel):
    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    id: str
    name: str
    refs: Ref

    # Additional
    org_login: str

@app.asset(
    node=NodeDef(
        kind=nk.REPOSITORY,
        description="GitHub Repository",
        icon="box-archive",
        properties=GHRepositoryProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.ORGANIZATION,
            end=nk.REPOSITORY,
            kind=ek.OWNS,
            description="Org owns repository",
            traversable=True,
        ),
    ],
)
class Repository(BaseAsset):
    """One record from the `repositories` DLT table → one GH_Repository node + GH_Owns edge from owner."""

    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    id: int
    node_id: str
    name: str
    full_name: str

    private: bool
    owner: Owner
    html_url: str | None = None
    description: str | None = None
    created_at: str | None = None
    updated_at: str | None = None
    pushed_at: str | None = None
    archived: bool | None = None
    disabled: bool | None = None
    visibility: str | None = None
    default_branch: str | None = None
    open_issues_count: int | None = None
    allow_forking: bool | None = None
    web_commit_signoff_required: bool | None = None
    forks: int | None = None
    open_issues: int | None = None
    watchers: int | None = None
    actions_enabled: bool | None = None
    self_hosted_runners_enabled: bool | None = None

    # Additional
    org_login: str

    @property
    def org_node_id(self) -> str | None:
        return self._lookup.org_id_for_login(self.org_login)

    @property
    def owner_id(self) -> str:
        return self.owner.node_id

    @property
    def owner_name(self) -> str:
        return self.owner.login

    @property
    def as_node(self) -> GHNode:
        rid = self.node_id
        return GHNode(
            kinds=[nk.REPOSITORY],
            properties=GHRepositoryProperties(
                name=self.name,
                displayname=self.full_name,
                node_id=rid,
                full_name=self.full_name,
                private=self.private,
                html_url=self.html_url,
                description=self.description,
                created_at=self.created_at,
                updated_at=self.updated_at,
                pushed_at=self.pushed_at,
                archived=self.archived,
                disabled=self.disabled,
                visibility=self.visibility,
                default_branch=self.default_branch,
                open_issues_count=self.open_issues_count,
                allow_forking=self.allow_forking,
                web_commit_signoff_required=self.web_commit_signoff_required,
                forks=self.forks,
                open_issues=self.open_issues,
                watchers=self.watchers,
                owner_name=self.owner_name or "",
                owner_id=self.owner_id or "",
                environment_name=self.org_login,
                environmentid=self.org_node_id,
                actions_enabled=self.actions_enabled,
                self_hosted_runners_enabled=self.self_hosted_runners_enabled,
                # secret_scanning=self.secret_scanning,
                query_branches=f"MATCH p=(:GH_Repository {{node_id: '{rid}'}})-[:GH_HasBranch]->(:GH_Branch) RETURN p",
                query_protected_branches=f"MATCH p=(:GH_Repository {{node_id: '{rid}'}})-[:GH_HasBranch]->(:GH_Branch)<-[:GH_ProtectedBy]-(:GH_BranchProtectionRule) RETURN p",
                query_branch_protection_rules=f"MATCH p=(:GH_Repository {{node_id: '{rid}'}})-[:GH_Contains]->(:GH_BranchProtectionRule) RETURN p",
                query_roles=f"MATCH p=(:GH_RepoRole)-[*1..]->(:GH_Repository {{node_id: '{rid}'}}) RETURN p",
                query_teams=f"MATCH p=(:GH_Team)-[:GH_MemberOf|GH_HasRole*1..]->(:GH_RepoRole)-[]->(:GH_Repository {{node_id: '{rid}'}}) RETURN p",
                query_workflows=f"MATCH p=(:GH_Repository {{node_id:'{rid}'}})-[:GH_HasWorkflow]->(w:GH_Workflow) RETURN p",
                query_runners=f"MATCH p=(:GH_Repository {{node_id:'{rid}'}})-[:GH_CanUseRunner]->(:GH_Runner) RETURN p",
                query_environments=f"MATCH p=(:GH_Repository {{node_id: '{rid}'}})-[:GH_HasEnvironment]->(:GH_Environment) RETURN p",
                query_secrets=f"MATCH p=(:GH_Repository {{node_id:'{rid}'}})-[:GH_HasSecret]->(:GH_Secret) RETURN p",
                query_variables=f"MATCH p=(:GH_Repository {{node_id:'{rid}'}})-[:GH_HasVariable]->(:GH_Variable) RETURN p",
                query_secret_scanning_alerts=f"MATCH p=(:GH_Repository {{node_id:'{rid}'}})-[:GH_HasSecretScanningAlert]->(:GH_SecretScanningAlert) RETURN p",
                query_explicit_readers=f"MATCH p=(role:GH_Role)-[:GH_HasBaseRole|GH_ReadRepoContents*1..]->(r:GH_Repository {{node_id:'{rid}'}}) MATCH p1=(role)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
                query_unrolled_readers=f"MATCH p=(role:GH_Role)-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf|GH_ReadRepoContents*1..]->(r:GH_Repository {{node_id:'{rid}'}}) MATCH p1=(role)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
                query_explicit_writers=f"MATCH p=(role:GH_Role)-[:GH_HasBaseRole|GH_WriteRepoContents|GH_WriteRepoPullRequests*1..]->(r:GH_Repository {{node_id:'{rid}'}}) MATCH p1=(role)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
                query_unrolled_writers=f"MATCH p=(role:GH_Role)-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf|GH_WriteRepoContents|GH_WriteRepoPullRequests*1..]->(r:GH_Repository {{node_id:'{rid}'}}) MATCH p1=(role)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
            ),
        )

    @property
    def edges(self):
        if self.owner_id:
            yield Edge(
                kind=ek.OWNS,
                start=EdgePath(value=self.owner_id, match_by="id"),
                end=EdgePath(value=self.node_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )
