from dataclasses import dataclass
from typing import ClassVar

from dlt.common.libs.pydantic import DltConfig
from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import BaseModel, ConfigDict, Field

from openhound_github.graph import GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app


@dataclass
class GHTeamProperties(GHNodeProperties):
    """Team-specific properties and accordion panel queries.

    Attributes:
        collected: Collected/generated by OpenHound
        slug: The team's URL-safe slug identifier.
        description: The team's description.
        privacy: The team's privacy level (e.g., `visible`, `secret`).
        environment_name: The name of the environment (GitHub organization).
        query_first_degree_members: OpenGraph query for related first degree members.
        query_unrolled_members: OpenGraph query for related unrolled members.
        query_first_degree_maintainers: OpenGraph query for related first degree maintainers.
        query_unrolled_maintainers: OpenGraph query for related unrolled maintainers.
        query_repositories: OpenGraph query for related repositories.
        query_child_teams: OpenGraph query for related child teams.
    """

    collected: bool = True

    # TODO: Check permissions field
    slug: str | None = None
    description: str | None = None
    privacy: str | None = None
    environment_name: str | None = None

    query_first_degree_members: str | None = None
    query_unrolled_members: str | None = None
    query_first_degree_maintainers: str | None = None
    query_unrolled_maintainers: str | None = None
    query_repositories: str | None = None
    query_child_teams: str | None = None


class MemberNode(BaseModel):
    id: str
    login: str


class MemberEdge(BaseModel):
    role: str
    node: MemberNode


class PageInfo(BaseModel):
    end_cursor: str = Field(alias="endCursor")
    has_next_page: bool = Field(alias="hasNextPage")


class Members(BaseModel):
    edges: list[MemberEdge]
    page_info: PageInfo = Field(alias="pageInfo")


class ParentTeam(BaseModel):
    id: str


@app.asset(
    node=NodeDef(
        kind=nk.TEAM,
        description="GitHub Team",
        icon="user-group",
        properties=GHTeamProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.TEAM,
            end=nk.TEAM,
            kind=ek.MEMBER_OF,
            description="Team is a child of parent team",
            traversable=False,
        ),
    ],
)
class Team(BaseAsset):
    """One record from the `teams` DLT table → one GH_Team node + optional GH_MemberOf edge to parent."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    name: str
    id: str
    database_id: int = Field(alias="databaseId")
    slug: str
    description: str | None = None
    privacy: str | None = None
    parent_team: ParentTeam | None = None
    org_node_id: str | None = None
    org_login: str | None = None

    # Used for overflow
    members: Members

    dlt_config: ClassVar[DltConfig] = {"return_validated_models": True}

    @property
    def node_id(self) -> str:
        """The ID from a GraphQL API response is the same as a regular node_id"""
        return self.id

    @property
    def as_node(self) -> GHNode:
        tid = self.node_id
        return GHNode(
            kinds=[nk.TEAM],
            properties=GHTeamProperties(
                name=self.name,
                displayname=self.name,
                node_id=tid,
                slug=self.slug,
                description=self.description,
                privacy=self.privacy,
                environment_name=self.org_login or self._lookup.org_login(),
                environmentid=self.org_node_id or self._lookup.org_id(),
                query_first_degree_members=f"MATCH p=(:GH_User)-[:GH_HasRole]->(t:GH_TeamRole)-[:GH_MemberOf]->(:GH_Team {{node_id:'{tid}'}}) RETURN p",
                query_unrolled_members=f"MATCH p=(teamrole:GH_TeamRole)-[:GH_MemberOf*1..]->(:GH_Team {{node_id:'{tid}'}}) MATCH p1 = (teamrole)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
                query_first_degree_maintainers=f"MATCH p=(:GH_User)-[:GH_HasRole]->(t:GH_TeamRole {{short_name: 'maintainers'}})-[:GH_MemberOf]->(:GH_Team {{node_id:'{tid}'}}) RETURN p",
                query_unrolled_maintainers=f"MATCH p=(teamrole:GH_TeamRole {{short_name: 'maintainers'}})-[:GH_MemberOf*1..]->(:GH_Team {{node_id:'{tid}'}}) MATCH p1 = (teamrole)<-[:GH_HasRole]-(:GH_User) RETURN p,p1",
                query_repositories=f"MATCH p=(:GH_Team {{node_id:'{tid}'}})-[:GH_HasRole]->(:GH_RepoRole)-[]->(:GH_Repository) RETURN p",
                query_child_teams=f"MATCH p=(:GH_Team)-[:GH_MemberOf*1..]->(:GH_Team {{node_id:'{tid}'}}) RETURN p",
            ),
        )

    @property
    def _bypass_pull_request_allowances_edges(self):
        """Edges from this User to Branch Protection rules if set in the BPR pull request allowances (GH_BypassPullRequestAllowances)"""
        bypass_branches = self._lookup.bypass_pull_request_allowances(self.node_id)
        for (rule_id,) in bypass_branches:
            yield Edge(
                kind=ek.BYPASS_PULL_REQUEST_ALLOWANCES,
                start=EdgePath(value=self.node_id, match_by="id"),
                end=EdgePath(value=rule_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _bypass_push_allowances_edges(self):
        bypass_branches = self._lookup.bypass_push_restrictions(self.node_id)
        for (rule_id,) in bypass_branches:
            yield Edge(
                kind=ek.RESTRICTIONS_CAN_PUSH,
                start=EdgePath(value=self.node_id, match_by="id"),
                end=EdgePath(value=rule_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        if self.parent_team:
            yield Edge(
                kind=ek.MEMBER_OF,
                start=EdgePath(value=self.node_id, match_by="id"),
                end=EdgePath(value=self.parent_team.id, match_by="id"),
                properties=EdgeProperties(traversable=False),
            )

        # yield from self._branch_edges
        yield from self._bypass_pull_request_allowances_edges
        yield from self._bypass_push_allowances_edges
