from dataclasses import dataclass, field

from openhound.core.asset import BaseAsset, EdgeDef, NodeDef
from openhound.core.models.entries_dataclass import Edge, EdgePath, EdgeProperties
from pydantic import Field

from openhound_github.graph import GHNode, GHNodeProperties
from openhound_github.kinds import edges as ek
from openhound_github.kinds import nodes as nk
from openhound_github.main import app


@dataclass
class GHUserProperties(GHNodeProperties):
    """User-specific properties with profile fields and accordion panel queries."""

    collected: bool = field(
        default=True, metadata={"description": "Collected/generated by OpenHound"}
    )
    login: str = field(
        default="", metadata={"description": "The user's GitHub login handle."}
    )
    full_name: str | None = field(
        default=None,
        metadata={"description": "The user's full name from their profile."},
    )
    company: str | None = field(
        default=None,
        metadata={"description": "The company listed on the user's profile."},
    )
    email: str | None = field(
        default=None, metadata={"description": "The user's public email address."}
    )
    environment_name: str = field(
        default="",
        metadata={
            "description": "The name of the environment (GitHub organization) the user belongs to."
        },
    )
    query_personal_access_tokens: str = ""
    query_roles: str = ""
    query_teams: str = ""
    query_repositories: str = ""
    query_branches: str = ""


@app.asset(
    node=NodeDef(
        kind=nk.USER,
        description="GitHub User",
        icon="user",
        properties=GHUserProperties,
    ),
    edges=[
        EdgeDef(
            start=nk.USER,
            end=nk.ORG_ROLE,
            kind=ek.HAS_ROLE,
            description="User has default org role (owners or members)",
            traversable=True,
        ),
    ],
)
class User(BaseAsset):
    """One record from the `users` DLT table → one GH_User node + GH_HasRole edge to default org role."""

    id: str
    database_id: int | None = Field(alias="databaseId", default=None)
    login: str
    name: str | None = None
    email: str | None = None
    company: str | None = None
    org_role: str = Field(alias="role")

    # Additional
    org_login: str

    @property
    def org_node_id(self) -> str | None:
        return self._lookup.org_id_for_login(self.org_login)

    @property
    def node_id(self) -> str:
        """The ID from a GraphQL API response is the same as a regular node_id"""
        return self.id

    @property
    def _org_node_id(self) -> str:
        return self.org_node_id

    @property
    def _org_login(self) -> str:
        return self.org_login

    @property
    def as_node(self) -> GHNode:
        uid = self.node_id
        org_node_id = self._org_node_id
        org_login = self._org_login
        return GHNode(
            kinds=[nk.USER],
            properties=GHUserProperties(
                name=self.login,
                displayname=self.name or self.login,
                node_id=uid,
                login=self.login,
                full_name=self.name,
                company=self.company,
                email=self.email,
                environment_name=org_login,
                environmentid=org_node_id,
                query_personal_access_tokens=(
                    f"MATCH p=(:GH_User {{node_id: '{uid}'}})-[]->(token) "
                    f"WHERE token:GH_PersonalAccessToken OR token:GH_PersonalAccessTokenRequest RETURN p"
                ),
                query_roles=(
                    f"MATCH p=(t:GH_User {{node_id:'{uid}'}})"
                    f"-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf*1..]->(:GH_Role) RETURN p"
                ),
                query_teams=(
                    f"MATCH p=(:GH_User {{node_id:'{uid}'}})"
                    f"-[:GH_HasRole]->(t:GH_TeamRole)-[:GH_MemberOf*1..4]->(:GH_Team) RETURN p"
                ),
                query_repositories=(
                    f"MATCH p=(t:GH_User {{node_id:'{uid}'}})"
                    f"-[:GH_HasRole|GH_HasBaseRole|GH_MemberOf*1..]->(:GH_RepoRole)"
                    f"-[:GH_ReadRepoContents|GH_WriteRepoContents|GH_WriteRepoPullRequests"
                    f"|GH_ManageWebhooks|GH_ManageDeployKeys|GH_PushProtectedBranch"
                    f"|GH_DeleteAlertsCodeScanning|GH_ViewSecretScanningAlerts"
                    f"|GH_RunOrgMigration|GH_BypassBranchProtection|GH_EditRepoProtections]"
                    f"->(:GH_Repository) RETURN p"
                ),
                query_branches=(
                    f"MATCH p=(:GH_User {{node_id:'{uid}'}})"
                    f"-[r]->(:GH_BranchProtectionRule)-[:GH_ProtectedBy]->(:GH_Branch) RETURN p"
                ),
            ),
        )

    @property
    def _bypass_pull_request_allowances_edges(self):
        """Edges from this User to Branch Protection rules if set in the BPR pull request allowances (GH_BypassPullRequestAllowances)"""
        bypass_branches = self._lookup.bypass_pull_request_allowances(self.node_id)
        for (rule_id,) in bypass_branches:
            yield Edge(
                kind=ek.BYPASS_PULL_REQUEST_ALLOWANCES,
                start=EdgePath(value=self.node_id, match_by="id"),
                end=EdgePath(value=rule_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def _bypass_push_allowances_edges(self):
        bypass_branches = self._lookup.bypass_push_restrictions(self.node_id)
        for (rule_id,) in bypass_branches:
            yield Edge(
                kind=ek.RESTRICTIONS_CAN_PUSH,
                start=EdgePath(value=self.node_id, match_by="id"),
                end=EdgePath(value=rule_id, match_by="id"),
                properties=EdgeProperties(traversable=True),
            )

    @property
    def edges(self):
        org_node_id = self._org_node_id
        role_node_id = (
            f"{org_node_id}_owners"
            if self.org_role == "ADMIN"
            else f"{org_node_id}_members"
        )
        yield Edge(
            kind=ek.HAS_ROLE,
            start=EdgePath(value=self.node_id, match_by="id"),
            end=EdgePath(value=role_node_id, match_by="id"),
            properties=EdgeProperties(traversable=True),
        )

        # DONE
        yield from self._bypass_pull_request_allowances_edges
        yield from self._bypass_push_allowances_edges
